#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "meet"
name = "Meet"
description.en = "Simple and Secure Video Conferencing. Powered by LiveKit."
description.fr = "Solution simple et sécurisée de visioconférence. Propulsée par Livekit."

version = "1.0.1~ynh1"

maintainers = ["fflorent", "rouja"]

[upstream]
license = "MIT"
website = "https://visio.numerique.gouv.fr/"
demo = "https://visio.numerique.gouv.fr/"
code = "https://github.com/suitenumerique/meet"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false

sso = true

disk = "1.5G"
ram.build = "1G"
ram.runtime = "200M"

[install]
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr-fr", "en-us"]
    default = "fr-fr"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/meet/archive/refs/tags/v1.0.1.tar.gz"
    sha256 = "f4f7779fd03614d345d9cd0cf4cb0452803ac8f3089681b7abd7f93cb48c9a39"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.9.9/livekit_1.9.9_linux_amd64.tar.gz"
    amd64.sha256 = "d83737022884aa4ec401377529c2a6a4a68ddc1ea29ed2b266172057c3081a88"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.9.9/livekit_1.9.9_linux_arm64.tar.gz"
    arm64.sha256 = "02bb2c858f51281eee75b6404622d28272aac228fdd5eff3cdb2635a8cef4ee6"
    armhf.url = "https://github.com/livekit/livekit/releases/download/v1.9.9/livekit_1.9.9_linux_armv7.tar.gz"
    armhf.sha256 = "e1b600e32197bc691f534e93d9a93f25a4ecdd1c7d2f05999cacfd5c4ce52c71"
    in_subdir=false
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    backend.default = 8071
    # Ports for livekit
    # Documentation here: https://docs.livekit.io/home/self-hosting/ports-firewall/
    livekit.default = 7880 # Handled by nginx with SSL termination, on port 443
    tcp.default = 7881
    tcp.exposed = "TCP"

    [resources.apt]
    packages = "redis, python3, python3-venv, python3-setuptools, python3-pip, postgresql, rdfind"

    [resources.database]
    type = "postgresql"
