#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "lasuite-meet"
name = "La Suite - Meet"
description.en = "Simple and Secure Video Conferencing"
description.fr = "Solution simple et sécurisée de visioconférence"

version = "1.3.0~ynh1"

maintainers = ["fflorent", "rouja"]

[upstream]
license = "MIT"
website = "https://visio.numerique.gouv.fr/"
demo = "https://visio.numerique.gouv.fr/"
code = "https://github.com/suitenumerique/meet"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false
sso = true

disk = "1.5G"
ram.build = "1G"
ram.runtime = "200M"

[install]

    # TODO: Once removed, also remove the Prerequisites section of the description
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"

    [install.turn_domain]
    type = "domain"
    ask.en = "Select another domain for the Turn server (it will be created for you)"
    ask.fr = "Sélectionnez un autre domaine pour le serveur Turn (qui sera créé pour vous)"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr-fr", "en-us"]
    default = "fr-fr"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/meet/archive/refs/tags/v1.3.0.tar.gz"
    sha256 = "2d53ad0f38d0bf6fffdf07681eff2b422749277567608d87dcebb3e4f2ef7a17"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.9.10/livekit_1.9.10_linux_amd64.tar.gz"
    amd64.sha256 = "25d089ac54e6303b784ceaaadbdbb788aa22262c879245ed7409e1164e3591b7"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.9.10/livekit_1.9.10_linux_arm64.tar.gz"
    arm64.sha256 = "f95167dd5cfe88b9bea7e0b1318a0dd59f217f453245e9e6f22beb0a92cb8e55"
    armhf.url = "https://github.com/livekit/livekit/releases/download/v1.9.10/livekit_1.9.10_linux_armv7.tar.gz"
    armhf.sha256 = "76e3eaf39e60d849db092c01c1855028509d1bb73c99e270e3391de431c5770a"
    in_subdir=false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/livekit/livekit"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.arm64 = ".*arm64.tar.gz"
    autoupdate.asset.armhf = ".*armv7.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    turn.url = "__TURN_DOMAIN__/"
    turn.show_tile = false
    turn.allowed = "visitors"

    [resources.ports]
    backend.default = 8071
    # Ports for livekit
    # Documentation here: https://docs.livekit.io/home/self-hosting/ports-firewall/
    livekit.default = 7880 # Handled by nginx with SSL termination, on port 443
    tcp.default = 7881
    tcp.exposed = "TCP"

    turn.default = 5349

    turn_udp.default = 3478
    turn_udp.exposed = "UDP"

    [resources.apt]
    packages = "redis, python3, python3-venv, python3-setuptools, python3-pip, postgresql, rdfind"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
